# Generated by Django 4.2.2 on 2023-07-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['email'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
    ]
