# Generated by Django 4.2.2 on 2023-07-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['articulo'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
